import{i as l,a as S,S as b}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const c="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEYSURBVHgBrZZRDoIwDIYrwfDqTeQo3ohxEr0BXsW77GXFOFdkYcC6DuFPCJB1/7fCWgBgZEzfIPY256BYzqfkzE8nUNbCE+DzgqSKK8W6OVBV5xYk+ZUbgw/IFMVKmfxtng3ZYy5CjjBnISlzrXUtGcZiZpDxolsGIWItvTi/OK0xAuk7GhsBRjEGioNMmffMXKNEAAeRzENACYJc8QxF5IuJNBZhS2PSfBGwhNB9rjmpgHxZ5jqprAyC3jT0mi29RwSE5v6xhO9EhAjblN0tqS38G59t02ShKeCzU2Kh+SDE9z0GAUGxGPKaLS4F2aqVudcRENb8CIhovgeSMl/VwdQWbOPOl5yPvivs25b2MWjKJOu3hTX+AgZ5PpvL0NSkAAAAAElFTkSuQmCC",s={form:document.querySelector("form"),list:document.querySelector(".gallery"),spanLoader:document.querySelector(".loader"),loadButton:document.querySelector(".load-button"),input:document.querySelector(".form-input")};s.loadButton.addEventListener("click",v);s.form.addEventListener("submit",F);let u="",d=1;const p=15;async function F(e){if(e.preventDefault(),u=s.input.value.trim(),s.list.innerHTML="",s.loadButton.classList.add("hidden"),u==="")return l.error({messageColor:"#FFF",color:"#EF4040",iconUrl:c,position:"topRight",message:"Please,enter what do you want to find!"});d=1;try{const{hits:t,totalHits:n}=await f();E(t),h(t),L(n,p)}catch(t){l.error({messageColor:"#FFF",color:"#EF4040",iconUrl:c,position:"topRight",message:`${t}`})}m(),s.form.reset()}async function f(){s.spanLoader.classList.remove("hidden");const e=await S.get("https://pixabay.com/api/",{params:{key:"42112521-3ff4dfc201bab0977369cd2bc",q:`${u}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:p,page:d}}),{hits:t,totalHits:n}=e.data;return s.spanLoader.classList.add("hidden"),{hits:t,totalHits:n}}function E(e){e.length===0&&l.error({messageColor:"#FFF",color:"#EF4040",iconUrl:c,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function h(e){const t=e.map(({largeImageURL:n,webformatURL:i,tags:o,likes:r,views:a,comments:A,downloads:y})=>`<li class='gallery-item'>
           <a class='gallery-link' href='${n}'>
             <img class='gallery-image' src='${i}' alt='${o}'/>
           </a>
           <div class='container-app'>
            <p><span>Likes</span> ${r}</p>
            <p><span>Views</span> ${a}</p>
            <p><span>Comments</span> ${A}</p>
            <p><span>Downloads</span> ${y}</p>
           </div>
          </li>`).join("");s.list.insertAdjacentHTML("beforeend",t)}function m(){let e=new b(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});e.on("show.simpleLightbox"),e.refresh()}function L(e,t){Math.ceil(e/t)>1&&s.loadButton.classList.remove("hidden")}function B(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}async function v(){d++;try{const{hits:e,totalHits:t}=await f();h(e),C(d,t,p)}catch(e){console.log(e),l.error({messageColor:"#FFF",color:"#EF4040",iconUrl:c,position:"topRight",message:`${e}`})}B(),m()}function C(e,t,n){const i=Math.ceil(t/n);e>=i?(g.observe(s.list.lastChild),s.loadButton.classList.add("hidden")):g.unobserve(s.list.lastChild)}const g=new IntersectionObserver(w);function w(e,t){e.forEach(n=>{n.isIntersecting&&l.error({position:"topRight",messageColor:"#FFF",color:"#EF4040",iconUrl:c,message:"We're sorry, but you've reached the end of search results"})})}
//# sourceMappingURL=commonHelpers.js.map
